site_name: "HackRecon"
repo_url: https://github.com/EmilienPer/Discovery
site_author: EmilienPer
docs_dir: docs
pages:
  - Introduction: index.md
  - Installation: install.md
  - Usage: usage.md
  - Options: options.md
  - Reporting: report.md
extra:
  mailto: code@emilienperetti.be
theme: readthedocs
markdown_extensions:
  - admonition